"""
Builds two Jupyter notebooks for the fake news detection project:
  1. notebooks/01_project_walkthrough.ipynb  -- narrative review of the
     full pipeline: data, EDA, features, and final results, for viewing.
  2. notebooks/02_model_inference_and_checking.ipynb -- loads the best
     model, retrains it (fast: Logistic Regression on TF-IDF), and lets
     you test it on custom text or inspect its test-set errors directly.
"""

import nbformat as nbf

def md(text):
    return nbf.v4.new_markdown_cell(text)

def code(text):
    return nbf.v4.new_code_cell(text)


# =========================================================================
# Notebook 1: Project Walkthrough
# =========================================================================

nb1 = nbf.v4.new_notebook()
nb1.cells = [
    md("# Fake News Detection -- Project Walkthrough\n\n"
       "A narrative tour of the full pipeline: dataset, cleaning, feature engineering, "
       "and final model results. This notebook is for **viewing and reviewing** the project; "
       "it reads already-generated data/results rather than re-running the (slow) heavy steps "
       "like Word2Vec training or Random Forest tuning. For hands-on model testing, see "
       "`02_model_inference_and_checking.ipynb`."),

    md("## 1. Setup"),
    code("import pandas as pd\n"
         "import numpy as np\n"
         "import json\n"
         "from pathlib import Path\n"
         "from IPython.display import Image, display\n\n"
         "DATA_DIR = Path('../data')\n"
         "REPORTS_DIR = Path('../reports')\n"
         "FIG_DIR = REPORTS_DIR / 'figures'\n\n"
         "pd.set_option('display.max_colwidth', 80)"),

    md("## 2. Dataset Overview\n\n"
       "Loads the cleaned dataset (output of `src/day1_load_data.py` + `src/day2_clean_tokenize.py`). "
       "Run those scripts first if `combined_cleaned.csv` doesn't exist yet."),
    code("df = pd.read_csv(DATA_DIR / 'combined_cleaned.csv')\n"
         "print(f'Shape: {df.shape}')\n"
         "print(f'Class balance: {df[\"label\"].value_counts(normalize=True).round(3).to_dict()}  (0=Real, 1=Fake)')\n"
         "df[['title', 'label', 'text_token_count']].head(10)"),

    md("### Before / After Cleaning Example\n\n"
       "Shows the effect of manual cleaning, tokenization, stopword removal, and the "
       "Reuters-dateline strip (see Section 2.3 of the report for why that mattered)."),
    code("sample = df.iloc[0]\n"
         "print('RAW TEXT:\\n', sample['text'][:300], '\\n')\n"
         "print('CLEANED TEXT:\\n', sample['text_clean'][:300])"),

    md("## 3. Exploratory Data Analysis\n\n"
       "Figures generated by `src/day3_eda.py`."),
    code("display(Image(filename=str(FIG_DIR / '01_class_balance.png')))"),
    code("display(Image(filename=str(FIG_DIR / '02_article_length_distribution.png')))"),
    code("display(Image(filename=str(FIG_DIR / '04_top_words_by_label.png')))"),

    md("## 4. Feature Engineering Summary\n\n"
       "Three feature representations were built (Bag-of-Words, TF-IDF, Word2Vec embeddings), "
       "all from scratch -- see `src/day4_bag_of_words.py`, `day5_tfidf.py`, `day6_embeddings.py`. "
       "`day7_consolidate_features.py` validates they're all row-aligned with the labels."),
    code("import sys\n"
         "sys.path.insert(0, '../src')\n"
         "from day7_consolidate_features import load_feature_set, FEATURE_FILES\n\n"
         "for name in FEATURE_FILES:\n"
         "    X_train, X_test, y_train, y_test = load_feature_set(name)\n"
         "    print(f'{name:12s} train={X_train.shape}  test={X_test.shape}')"),

    md("## 5. Final Model Comparison\n\n"
       "Consolidated results from all four models across all three feature sets "
       "(`src/day14_consolidate_results.py`)."),
    code("comparison = pd.read_csv(REPORTS_DIR / 'final_model_comparison.csv')\n"
         "comparison"),

    code("display(Image(filename=str(FIG_DIR / '05_final_model_comparison.png')))"),
    code("display(Image(filename=str(FIG_DIR / '09_model_feature_heatmap.png')))"),

    md("## 6. ROC and Precision-Recall Curves"),
    code("display(Image(filename=str(FIG_DIR / '07_roc_curves.png')))"),
    code("display(Image(filename=str(FIG_DIR / '08_precision_recall_curves.png')))"),

    md("## 7. Cross-Validation / Robustness\n\n"
       "Confirms the single-split results above aren't a lucky/unlucky train-test split."),
    code("with open(REPORTS_DIR / 'day12_cv_tuning_results.json') as f:\n"
         "    cv_results = json.load(f)\n\n"
         "for model_name, res in cv_results.items():\n"
         "    best = res.get('best', res)\n"
         "    print(f\"{model_name:12s} acc={best.get('accuracy_mean', '?')} +/- {best.get('accuracy_std', '?')}\")\n\n"
         "with open(REPORTS_DIR / 'day13_nn_robustness_results.json') as f:\n"
         "    nn_robust = json.load(f)\n"
         "print(f\"neural_network  acc={nn_robust['summary']['accuracy']['mean']:.4f} \"\n"
         "      f\"+/- {nn_robust['summary']['accuracy']['std']:.4f}  (5 seeds, {nn_robust['feature_set']})\")"),

    md("## 8. Key Takeaways\n\n"
       "1. **Logistic Regression** (parametric) was the best overall model -- simplest model, best result.\n"
       "2. **KNN** (non-parametric) swung from 82% to 95% accuracy purely from changing feature representation -- "
       "a direct demonstration of the curse of dimensionality.\n"
       "3. Two feature-leakage issues (`subject` category, Reuters dateline) were caught during EDA and corrected "
       "before modeling -- without this, reported accuracy would have been an artifact, not a real result.\n"
       "4. The top predictive words reflect **formatting/sourcing style**, not fact-checking -- an important "
       "scope limitation, detailed in the full report's Discussion section.\n\n"
       "See `reports/Fake_News_Detection_IEEE_Report.docx` for the complete writeup, and "
       "`02_model_inference_and_checking.ipynb` to test the model on your own text."),
]


# =========================================================================
# Notebook 2: Model Inference and Checking
# =========================================================================

nb2 = nbf.v4.new_notebook()
nb2.cells = [
    md("# Model Inference and Checking\n\n"
       "Loads the best-performing configuration (Logistic Regression on TF-IDF -- retrains in "
       "well under a second, no need to persist a model file) and lets you:\n"
       "1. Classify your own custom text as Real or Fake\n"
       "2. Inspect the model's actual test-set errors\n"
       "3. Spot-check predictions against ground truth\n\n"
       "Run `src/day1_load_data.py` through `src/day9_logistic_regression.py` at least once "
       "before using this notebook, so the required data/feature files exist."),

    md("## 1. Setup and Load Artifacts"),
    code("import sys, json\n"
         "sys.path.insert(0, '../src')\n"
         "import numpy as np\n"
         "import pandas as pd\n"
         "from sklearn.linear_model import LogisticRegression\n"
         "from sklearn.metrics import classification_report, confusion_matrix\n\n"
         "from day7_consolidate_features import load_feature_set\n"
         "from day2_clean_tokenize import process_row  # same cleaning used throughout the project\n\n"
         "DATA_DIR = '../data'\n"
         "REPORTS_DIR = '../reports'"),

    md("## 2. Load the Best Config and Retrain\n\n"
       "Reads the winning feature set + hyperparameter from `day9_logreg_results.json` "
       "(same pattern used by `day12`-`day15`), so this always reflects your actual best result, "
       "not a hardcoded guess."),
    code("with open(f'{REPORTS_DIR}/day9_logreg_results.json') as f:\n"
         "    logreg_results = json.load(f)\n"
         "best = max(logreg_results, key=lambda r: r['accuracy'])\n"
         "feature_set, C = best['feature_set'], best['C']\n"
         "print(f'Using feature_set={feature_set}, C={C}  (test accuracy was {best[\"accuracy\"]:.4f})')\n\n"
         "X_train, X_test, y_train, y_test = load_feature_set(feature_set)\n"
         "model = LogisticRegression(C=C, max_iter=1000, random_state=42)\n"
         "model.fit(X_train, y_train)\n"
         "print('Model trained.')"),

    md("## 3. Load the Vocabulary and IDF Values\n\n"
       "Needed to convert new, raw text into the same TF-IDF feature space the model was trained on."),
    code("with open(f'{DATA_DIR}/bow_vocabulary.json') as f:\n"
         "    vocabulary = json.load(f)\n"
         "idf = np.load(f'{DATA_DIR}/idf_values.npy')\n"
         "print(f'Vocabulary size: {len(vocabulary)}')"),

    md("## 4. Build a Prediction Function\n\n"
       "Reuses the exact same cleaning/tokenization pipeline as the rest of the project "
       "(`day2_clean_tokenize.process_row`), so predictions are consistent with how the model was trained."),
    code("from scipy import sparse\n\n"
         "def text_to_tfidf_vector(raw_text):\n"
         "    tokens = process_row(raw_text)\n"
         "    doc_len = len(tokens)\n"
         "    vec = np.zeros(len(vocabulary))\n"
         "    if doc_len == 0:\n"
         "        return sparse.csr_matrix(vec)\n"
         "    from collections import Counter\n"
         "    counts = Counter(tokens)\n"
         "    for word, count in counts.items():\n"
         "        col_idx = vocabulary.get(word)\n"
         "        if col_idx is not None:\n"
         "            tf = count / doc_len\n"
         "            vec[col_idx] = tf * idf[col_idx]\n"
         "    norm = np.linalg.norm(vec)\n"
         "    if norm > 0:\n"
         "        vec = vec / norm\n"
         "    return sparse.csr_matrix(vec)\n\n"
         "def predict_fake_or_real(raw_text, verbose=True):\n"
         "    vec = text_to_tfidf_vector(raw_text)\n"
         "    prob_fake = model.predict_proba(vec)[0, 1]\n"
         "    label = 'FAKE' if prob_fake >= 0.5 else 'REAL'\n"
         "    if verbose:\n"
         "        print(f'Prediction: {label}   (P(fake) = {prob_fake:.3f})')\n"
         "    return label, prob_fake"),

    md("## 5. Try It Yourself\n\n"
       "Edit the text below and re-run the cell to test the model on your own examples."),
    code("predict_fake_or_real(\n"
         "    \"WASHINGTON (Reuters) - The Senate voted on Tuesday to advance a bipartisan \"\n"
         "    \"infrastructure bill after months of negotiation between lawmakers.\"\n"
         ")\n\n"
         "predict_fake_or_real(\n"
         "    \"You won't believe what this celebrity said about the government, click to \"\n"
         "    \"see the shocking photos that they don't want you to see!\"\n"
         ")"),

    md("## 6. Spot-Check Against Real Test-Set Articles\n\n"
       "Pulls a few random test-set articles and compares the model's prediction to the true label."),
    code("test_df = pd.read_csv(f'{DATA_DIR}/test.csv')\n"
         "sample = test_df.sample(5, random_state=7)\n\n"
         "for _, row in sample.iterrows():\n"
         "    true_label = 'FAKE' if row['label'] == 1 else 'REAL'\n"
         "    pred_label, prob = predict_fake_or_real(row['text'], verbose=False)\n"
         "    correct = '✓' if pred_label == true_label else '✗ MISCLASSIFIED'\n"
         "    print(f\"{correct}  true={true_label:4s}  pred={pred_label:4s}  \"\n"
         "          f\"P(fake)={prob:.3f}  title={row['title'][:70]}\")"),

    md("## 7. Full Test-Set Evaluation\n\n"
       "Confirms this notebook's retrained model reproduces the metrics reported in the project "
       "(should match `day9_logreg_results.json` closely)."),
    code("preds = model.predict(X_test)\n"
         "print(classification_report(y_test, preds, target_names=['Real', 'Fake']))\n"
         "print('Confusion matrix [[TN, FP], [FN, TP]]:')\n"
         "print(confusion_matrix(y_test, preds))"),

    md("## 8. Inspect Misclassified Examples\n\n"
       "Useful for spot-checking *why* the model got something wrong -- e.g., does it lack "
       "the usual formatting cues discussed in the report's Discussion section?"),
    code("preds_full = model.predict(X_test)\n"
         "test_df_reset = test_df.reset_index(drop=True)\n"
         "misclassified_idx = np.where(preds_full != y_test)[0]\n"
         "print(f'{len(misclassified_idx)} / {len(y_test)} test articles misclassified\\n')\n\n"
         "for idx in misclassified_idx[:5]:\n"
         "    row = test_df_reset.iloc[idx]\n"
         "    true_label = 'FAKE' if row['label'] == 1 else 'REAL'\n"
         "    pred_label = 'FAKE' if preds_full[idx] == 1 else 'REAL'\n"
         "    print(f\"true={true_label}  pred={pred_label}  title={row['title'][:80]}\")"),
]

nbf.write(nb1, 'notebooks/01_project_walkthrough.ipynb')
nbf.write(nb2, 'notebooks/02_model_inference_and_checking.ipynb')
print("Notebooks written.")